### ISSUE TITLE
Files number input

### ISSUE THREAD

**Issue by sepandhaghighi** [sepandhaghighi/pyrgg#42]
#### Description
Get files number from user

**Comment by ahmadsalimi** [comment]
> #### Description
> Get files number from user

@sepandhaghighi What do you mean by **files number** here?

**Comment by sepandhaghighi** [comment]
> > #### Description
> > Get files number from user
> 
> @sepandhaghighi What do you mean by **files number** here?

Number of files to generate with the current setting.
For example, a user wants to generate two random graphs with the same setting
