### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by sepandhaghighi** [sepandhaghighi/pyrgg#43]
#### Description
Save and load different configs in a config file

**Comment by ahmadsalimi** [comment]
> #### Description
> Save and load different configs in a config file

Could you please explain what do you exactly mean by **config**?

**Comment by ahmadsalimi** [comment]
> #### Description
> Save and load different configs in a config file

@sepandhaghighi  Could you please explain what do you exactly mean by **config**?

**Comment by sepandhaghighi** [comment]
> > #### Description
> > Save and load different configs in a config file
> 
> @sepandhaghighi Could you please explain what do you exactly mean by **config**?

Save the setting as a config file (for example JSON style) and then load it
