### ISSUE TITLE
Bug in generating of multigraphs

### ISSUE THREAD

**Issue by sepandhaghighi** [sepandhaghighi/pyrgg#59]
#### Description
Bug in generating of multigraphs
#### Steps/Code to Reproduce
![image](https://user-images.githubusercontent.com/7515099/91654583-4544a080-eabf-11ea-9842-9351614f4164.png)

#### Expected Behavior
Total Number of Edges ~ 10000
#### Actual Behavior
Total Number of Edges ~ 5
#### Operating System
Windows 10
#### Python Version
3.5.2
#### Pyrgg Version
0.8

**Comment by sadrasabouri** [comment]
Is it specially related to 15 (GEXF) or this is a general bug about all formats?

**Comment by sepandhaghighi** [comment]
> Is it specially related to 15 (GEXF) or this is a general bug about all formats?

No it is a general bug related to `input_filter` function conditions
