### ISSUE TITLE
Graph Plotting

### ISSUE THREAD

**Issue by sadrasabouri** [sepandhaghighi/pyrgg#65]
#### Description
Sometimes it can be useful if we make a visualized output which helps the user making some sort of illustration about recently made graph.

It can be shown after each time of generation in `pyrgg` menu.
`networkX` has something like this, you can see it in the link bellow:
https://www.python-course.eu/networkx.php
<img src="https://www.python-course.eu/images/simple_path.png">

**Comment by sadrasabouri** [comment]
@sepandhaghighi I found new library for graph plotting ([graph-tool](https://graph-tool.skewed.de/)).
It claims that it's lightweight version of `networkx`. Can you double check it if it's suitable for us?

**Comment by sadrasabouri** [comment]
We decided that plotting graph is not the goal of this repository, so I'm closing this issue.

**Comment by tuxiqae** [comment]
I understand that visualization is not the goal of `pyrgg`, but maybe adding a couple of battle-tested examples on how to use other projects in order to visualize the graphs generated using `pyrgg` would be best.
