### ISSUE TITLE
Convert JSON numeric values to integers

### ISSUE THREAD

**Issue by tuxiqae** [sepandhaghighi/pyrgg#82]
#### Description
Currently when a new JSON graph is created all numeric values are written as strings even though they can be integers.

#### Expected Behavior
Have a JSON file with IDs, (including "source" and "target") as integers.

#### Actual Behavior
All those fields are strings

#### Pyrgg Version
v1.0

**Comment by sepandhaghighi** [comment]
@tuxiqae Good point 💯 
We will work on this issue on a future release
