### ISSUE TITLE
Remove the 'graph' object from the JSON

### ISSUE THREAD

**Issue by tuxiqae** [sepandhaghighi/pyrgg#83]
#### Description
Currently when a new JSON graph is being generated, PyRGG generates a `graph` object which is redundant. 

#### Expected Behavior
Have `nodes` and `edges` in the root of the JSON file:
```json
{
    "nodes" : [
      {"id": "1"},
      {...}
    ],
    "edges" : [
      {    
        "source": "1",
        "target": "4",
        "weight": "8"
      },
      {...}
    ]
  }
```

If it is done because you are laying the ground for some future work regarding graph properties - you could maybe add a new `properties` objects at the JSON root.

#### Actual Behavior
```json
{
  "graph" : {
    "nodes" : [
      {"id": "1"},
      {...}
    ],
    "edges" : [
      {    
        "source": "1",
        "target": "4",
        "weight": "8"
      },
      {...}
    ]
  }
}
```

#### Pyrgg Version
v1.0

**Comment by sepandhaghighi** [comment]
@tuxiqae Thanks for your comment 🥇 
We need this format for some future work
