### ISSUE TITLE
Add directed graph support to JSON graphs

### ISSUE THREAD

**Issue by tuxiqae** [sepandhaghighi/pyrgg#84]
#### Description
When JSON files are generated using PyRGG, whether directed or not - there is no distinction in the JSON for it.

#### Expected Behavior
Add a new `properties` object to the root of the file which will contain details of the properties set in the generation such as:
- `directed`
- `signed`
- `multigraph`
- `weighted`
- `self loops`
- `signed`

All of those should be `boolean` variables.

#### Actual Behavior
Those properties can't be found currently.

#### Pyrgg Version
v1.0

**Comment by sepandhaghighi** [comment]
Good point 💯
