### ISSUE TITLE
Improve Branch Generator

### ISSUE THREAD

**Issue by sepandhaghighi** [sepandhaghighi/pyrgg#98]
#### Description
https://github.com/sepandhaghighi/pyrgg/blob/622bfceb091a54b7da7592cd80a8335a56eee26a/pyrgg/functions.py#L502

![image](https://user-images.githubusercontent.com/7515099/120245842-c49c1600-c283-11eb-8bd4-f34dd251436b.png)

This line is time-consuming (about 60% of the total time!!).
We need it only for tests, so I think we can bypass it by a flag in the normal run.

**Comment by sepandhaghighi** [comment]
@sadrasabouri What's your idea?
Please take a look at this issue 💯

**Comment by sadrasabouri** [comment]
Can you explain why do we need this line just in test?

**Comment by sepandhaghighi** [comment]
> Can you explain why do we need this line just in test?

Because of reproducibility, casting `set` to `list` changes order randomly
